apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: lukianov
  labels:
    app: nginx
type: Opaque
data:
  username: b2xlZw==
  password: MTIzNDU2Nzg=
  LDAP_PASSWORD: cGFzc3dvcmRfbGRhcA==
