FROM nginx:latest

WORKDIR /data

COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html  /usr/share/nginx/html
COPY entrypoint.sh /data
RUN chmod u+x entrypoint.sh

VOLUME /data

CMD ["/data/entrypoint.sh"]
