apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lukianov
  labels:
    app: nginx
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: nginx-secret
                key: username
          - name: NAME
            valueFrom:
              configMapKeyRef:
                name: nginx-config
                key: name
        envFrom:
          - configMapRef:
              name: nginx-config
        image: nginx

